import dotenv from 'dotenv';
dotenv.config();

export const ENV_VARS = {
    MONGODB: process.env.MONGODB,

    PORT: process.env.PORT || 8080,

    FRONTEND_URL: process.env.FRONTEND_URL,

    RESEND_API: process.env.RESEND_API,

    SECRET_KEY_ACCESS_TOKEN: process.env.SECRET_KEY_ACCESS_TOKEN,
    SECRET_KEY_REFRESH_TOKEN: process.env.SECRET_KEY_REFRESH_TOKEN,

    CLODINARY_CLOUD_NAME: process.env.CLODINARY_CLOUD_NAME,
    CLODINARY_API_KEY: process.env.CLODINARY_API_KEY,
    CLODINARY_API_SECRET_KEY: process.env.CLODINARY_API_SECRET_KEY,
    CLODINARY_ENVIRONMENTAL_VARIABLE: process.env.CLODINARY_ENVIRONMENTAL_VARIABLE,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_ENDPOINT_WEBHOOK_SECRET_KEY: process.env.STRIPE_ENDPOINT_WEBHOOK_SECRET_KEY
};